version: "3.6"

services:
  db:
    image: postgres:11.9
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tint
      - POSTGRES_PASSWORD=tint
      - PGPASSWORD=tint
      - POSTGRES_DB=tint

  app:
    image: node:16
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=tint
      - DB_NAME=tint
      - DB_PASSWORD=tint
    command: yarn start
